ALTER TABLE pic CHANGE COLUMN group_id group_id VARCHAR(128) NOT NULL COLLATE utf8_bin;
ALTER TABLE pic CHANGE COLUMN id_key id_key VARCHAR(128) NOT NULL COLLATE utf8_bin;
ALTER TABLE pic CHANGE COLUMN delete_key delete_key VARCHAR(128) NOT NULL COLLATE utf8_bin;


